Movies update
aryans1204/MOBLIMA pull request #10
Opened 2022-10-24 15:18 UTC by ChooJinCheng

**Movie.java** : Movie Entity that have all attributes of a movie
**MovieController**: (Conflicts with Aryans part)
-Implemented CRUD functions to manipulate all movie data into a local .dat file. (Using Serializable I/O)
-Datas are stored in a ArrayList<Movie>
**movieUI.java**: Sample UI to aid the process of CRUD for users
**Review.java**: Review entity that have all attributes of a review
**MovieType**: Enum Class
**MovieStatus**: Enum Class

2022-10-24 16:03 UTC, aryans1204 requested changes

2022-10-24 16:03 UTC, aryans1204 commented on movieUI.java
> +public class movieUI {
Please refactor the class name as MovieUI, all class names should begin with a capital letter to adhere with the Java class standard.

2022-10-24 16:03 UTC, aryans1204 commented on movieUI.java
> +	public static void updateMovieListing() {
I think it would be a better idea to have the updateMovieListing as a Staff method, since only staff can change the movie listing. However, since you've already implemented the MovieController, you might consider just moving this method over to Staff.java, and keeping the logic same(since the logic looks ok and is mostly similar to what I had previously written). So its basically just making this exact same method a Staff method instead of Movie

2022-10-24 16:03 UTC, aryans1204 commented on movieUI.java
> +	public static void removeMovieListing() {
same idea with this method, better to move over to Staff.

2022-10-24 16:03 UTC, aryans1204 commented on movieUI.java
> +	public static void createMovieListing() {
same idea here too, just move over to Staff, since this is a Staff method.

2022-10-24 16:03 UTC, aryans1204 commented on Review.java
> +
I don't see any problem with this, decoupling the Review class seems good and the username already fits in with my staff authentication method.

2022-10-24 16:03 UTC, aryans1204 commented on MovieType.java
> +
LGTM

2022-10-24 16:03 UTC, aryans1204 commented on MovieStatus.java
> +
LGTM

2022-10-24 16:03 UTC, aryans1204 commented on MovieController.java
> +	MovieController(){
constructor needs to be implemented.

2022-10-24 16:03 UTC, aryans1204 commented on MovieController.java
> +
On the whole, the CRUD implementation looks good to me. We can write TestBuilder class that uses your "write" methods to build the movie.dat file as well, I see no problem.

2022-10-24 16:03 UTC, aryans1204 commented on Movie.java
> +
make the required imports for MovieType, Review, MovieController and MovieStatus

2022-10-24 16:03 UTC, aryans1204 commented on Movie.java
> +	private LocalDate movieReleaseDate;
instead of movie release date, a list of movie showtimes might be more useful, since those influence client booking and prices as well.

2022-10-24 16:03 UTC, aryans1204 commented on Movie.java
> +@SuppressWarnings("serial")
apart from the suggested changes, Movie class looks good

2022-10-24 16:08 UTC, aryans1204 commented
Overall PR looks good! Once these changes are made, I think we should be ready to merge

2022-10-29 20:07 UTC, ChooJinCheng commented
Did not add the import of the other classes in Movie.java since they are kind of in the same package for the time being.
MovieUI.java for the time being is just for testing of all these methods, feel free to move the required codes into staff.java.
Updated MovieAbs with all the latest implementations so that y'all can refer to it and know what to expect from it

2022-10-30 15:10 UTC, aryans1204 approved these changes
LGTM 🚀

2022-10-30 15:10 UTC, merged